---
- hosts: all
  gather_facts: no
  vars:
  tasks:
  - name: install nginx
    package:
      name: nginx
      state: present

  - name: copy the index.html file
    copy:
      src: index.html
      dest: /usr/share/nginx/html
      #remote_src: yes

  - name: install nginx
    service:
      name: nginx
      state: started
