---
- hosts: node02
  gather_facts: yes
  vars:
  tasks:
  - name: create file facts.txt
    blockinfile:
      path: /root/facts.txt
      create: yes
      block: |
        This is Ansible managed node "{{ ansible_hostname }}"
        IP address of host is "{{ ansible_default_ipv4.address }}"
        Its OS family is "{{ ansible_os_family }}"

  - name: create a copy of the file
    copy:
      src: /root/facts.txt
      dest: /usr/share/nginx/html/index.html
      remote_src: yes
